- .gitignore
- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/controller/admin/Dashboard.java
- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/web/admin/admin.jsp
cập nhật nốt dashboard for day
> update not dasborad order for day

- SWP291_Team2_SE1829NJ/src/java/controller/admin/accountManagement.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
- SWP291_Team2_SE1829NJ/web/admin/accountManager.jsp
- SWP291_Team2_SE1829NJ/web/admin/managerhome.jsp
> khởi tạo accountManagement

- SWP291_Team2_SE1829NJ/web/admin/maincss/newcss.css
- SWP291_Team2_SE1829NJ/web/admin/staff.jsp
> CHINH SUA SWITH ROOM

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
> chỉnh sửa lại 1 xíu dườngdaanx

- SWP291_Team2_SE1829NJ/web/Component/footer.jsp
- SWP291_Team2_SE1829NJ/web/Component/setupCss.jsp
- SWP291_Team2_SE1829NJ/web/bootstrap/css/animate.css
- SWP291_Team2_SE1829NJ/web/client/aboutus.jsp
- SWP291_Team2_SE1829NJ/web/client/profile.jsp
- SWP291_Team2_SE1829NJ/web/client/wedding.jsp
> Linhnnhe171195 

- SWP291_Team2_SE1829NJ/web/homepage.jsp
- SWP291_Team2_SE1829NJ/web/layout/navbarmenu.jsp
- SWP291_Team2_SE1829NJ/web/rooms.jsp
> chinh sua lai cac file

- SWP291_Team2_SE1829NJ/web/homepage.jsp
- SWP291_Team2_SE1829NJ/web/rooms.jsp
> thu sua code thg cu khanh

- SWP291_Team2_SE1829NJ/src/java/controller/LoginController.java
- SWP291_Team2_SE1829NJ/src/java/dal/DBContext.java
- SWP291_Team2_SE1829NJ/web/layout/navbarmenu.jsp
> thu nghiem thanmh cong

- SWP291_Team2_SE1829NJ/src/java/controller/LoginController.java
- SWP291_Team2_SE1829NJ/src/java/controller/RoomSearchServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/admin/Dashboard.java
- SWP291_Team2_SE1829NJ/web/layout/navbarmenu.jsp
> cap nhat lai logout

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/controller/admin/accountManagement.java
- SWP291_Team2_SE1829NJ/src/java/controller/admin/roomManagement.java
- SWP291_Team2_SE1829NJ/src/java/dao/AccountDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/UserAccountDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/UserAccount.java
> tao them class java

- SWP291_Team2_SE1829NJ/src/java/dao/UserAccountDAO.java
> test backend useraccount

- SWP291_Team2_SE1829NJ/src/java/controller/admin/accCreate.java
- SWP291_Team2_SE1829NJ/src/java/controller/admin/accDelete.java
- SWP291_Team2_SE1829NJ/src/java/controller/admin/accEdit.java
- SWP291_Team2_SE1829NJ/src/java/dal/DBContext.java
- SWP291_Team2_SE1829NJ/src/java/dao/AccountDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Account.java
- SWP291_Team2_SE1829NJ/web/admin/accountManager.jsp
> update tien do

- SWP291_Team2_SE1829NJ/src/java/controller/manager/roomCreate.java
- SWP291_Team2_SE1829NJ/src/java/controller/manager/roomDelete.java
- SWP291_Team2_SE1829NJ/src/java/controller/manager/roomEdit.java
- SWP291_Team2_SE1829NJ/src/java/controller/manager/roomManage.java
- SWP291_Team2_SE1829NJ/src/java/dao/RoomDAO.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
> khởi tạo controller room

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
cáu trúc lại đường dẫn và cách code
> sửa lại xml

- SWP291_Team2_SE1829NJ/src/java/controller/room/roomCreate.java
- SWP291_Team2_SE1829NJ/src/java/controller/room/roomDelete.java
- SWP291_Team2_SE1829NJ/src/java/controller/room/roomEdit.java
- SWP291_Team2_SE1829NJ/src/java/controller/room/roomManage.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
chỉnh sửa và cấu trúc lại code
> chỉnh sửa và cấu trúc lại code

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/controller/room/roomCreate.java
- SWP291_Team2_SE1829NJ/src/java/controller/room/roomManagement.java
- SWP291_Team2_SE1829NJ/src/java/dao/RoomDAO.java
- SWP291_Team2_SE1829NJ/web/admin/accountManager.jsp
- SWP291_Team2_SE1829NJ/web/admin/roomCreate.jsp
- SWP291_Team2_SE1829NJ/web/admin/roomManager.jsp
- SWP291_Team2_SE1829NJ/web/layout/navbarmenu.jsp
> update code roomManagement

- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/BlogDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/FeedbackDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/HotelDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/MenuDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/TypeRoomDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/UserAccountDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/UserDAO.java
> sửa lại thành công

- SWP291_Team2_SE1829NJ/src/java/controller/SubmitFeedbackus.java
- SWP291_Team2_SE1829NJ/src/java/dao/FeedbackusDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Feedbackus.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
- SWP291_Team2_SE1829NJ/web/aboutus.jsp
> feedbackus

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/model/BookingItem.java
- SWP291_Team2_SE1829NJ/src/java/model/Cart.java
> cập nhật nốt

- SWP291_Team2_SE1829NJ/src/java/controller/AddFeedbackServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/ListBlogServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/RoomSearchServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/ViewBlogServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/ViewRoomServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/marketer/DeleteFeedbackServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/marketer/EditFeedbackServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/marketer/ListManageFeedback.java
- SWP291_Team2_SE1829NJ/src/java/dao/BlogDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/FeedbackDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/RoomDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/UserDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Count.java
- SWP291_Team2_SE1829NJ/src/java/model/Feedback.java
- SWP291_Team2_SE1829NJ/src/java/model/Room.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
- SWP291_Team2_SE1829NJ/web/blog.jsp
- SWP291_Team2_SE1829NJ/web/blogdetail.jsp
- SWP291_Team2_SE1829NJ/web/rooms.jsp
- SWP291_Team2_SE1829NJ/web/single_room.jsp
> hung với hiệp hợp tác

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/controller/CheckoutServlet.java
- SWP291_Team2_SE1829NJ/src/java/dal/DBContext.java
- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/RoomDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Bill.java
- SWP291_Team2_SE1829NJ/web/WEB-INF/web.xml
- SWP291_Team2_SE1829NJ/web/checkout.jsp
> xong cart + checkout by cod

- .gitignore
- SWP291_Team2_SE1829NJ/src/java/controller/CheckoutServlet.java
- SWP291_Team2_SE1829NJ/src/java/dal/DBContext.java
- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/src/java/dao/RoomDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Account.java
- SWP291_Team2_SE1829NJ/src/java/model/Bill.java
- SWP291_Team2_SE1829NJ/src/java/model/Booking.java
- SWP291_Team2_SE1829NJ/src/java/model/BookingItem.java
- SWP291_Team2_SE1829NJ/src/java/utils/DateUtil.java
> chỉnh sửa lại payment

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/controller/CheckoutServlet.java
- SWP291_Team2_SE1829NJ/src/java/controller/LoginController.java
- SWP291_Team2_SE1829NJ/src/java/controller/RegisterController.java
- SWP291_Team2_SE1829NJ/src/java/dal/DBContext.java
- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/src/java/model/Bill.java
- SWP291_Team2_SE1829NJ/web/login.jsp
- SWP291_Team2_SE1829NJ/web/register.jsp
> cập nhật lại login register

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/src/java/dao/BillDAO.java
- SWP291_Team2_SE1829NJ/web/profile.jsp
- SWP291_Team2_SE1829NJ/web/viewListOrder.jsp
> capaj nhật nốt bill user

- SWP291_Team2_SE1829NJ/nbproject/private/private.xml
- SWP291_Team2_SE1829NJ/web/single_room.jsp
commit nốt cho validate startDate
> commit nốt cho validate startDate

- SWP291_Team2_SE1829NJ/web/admin/admin.jsp
- SWP291_Team2_SE1829NJ/web/layout/navbarmenu.jsp
> Duchung2607
